### ISSUE TITLE
Issue on the giveaway page

### ISSUE THREAD

**Issue by IzaacJ** [gerritwalther/sg2o#158]
Hello.
It seems to have stopped working correctly. Don't know why, because it worked correctly yesterday 😮 

This error is showing up in the console for me:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'apply')
    at S.M (sg2o.user.js:6206:18)
    at Object.fY (sg2o.dart:103:26)
    at aX.dK (html_dart2js.dart:36818:55)
    at aX.cl (giveaway.dart:12:17)
    at be.b3 (giveaway_page.dart:11:14)
    at oq (endless_giveaway.dart:13:52)
    at sg2o.user.js:7884:66
    at sg2o.user.js:7880:55
    at dartProgram (sg2o.user.js:7882:179)
    at sg2o.user.js:7884:76
```

**Comment by gerritwalther** [comment]
I think it is my fault. I switched the server yesterday and thought it was working fine. I'm at work right now, but will check later to get a fix out.

**Comment by gerritwalther** [comment]
It should be working again, give it a try @IzaacJ
